### ISSUE TITLE
PHP Notice din cauza unui argument lipsă din funcția „register_rest_route”

### ISSUE THREAD

**Issue by vladutilie** [OblioSoftware/oblio-woocommerce#3]
Salut,

Folosesc modulul Oblio de WordPress pentru un magazin online și lucrând local cu modul depanare activat, am observat notificarea PHP de mai jos în fișierul `debug.log`:
```
[15-Jan-2024 10:22:03 UTC] PHP Notice:  Funcția register_rest_route a fost apelată incorect. Definiția rutei REST API pentru oblio/v1/card/confirm nu cuprinde argumentul permission_callback, care este necesar. Pentru rutele REST API care sunt destinate să fie publice, folosește __return_true ca un apel-înapoi pentru permisiuni. Te rog vezi <a>Depanare în WordPress</a> pentru mai multe informații. (Acest mesaj a fost adăugat în versiunea 5.5.0.) in /Users/vlad/www/mclass/wp-includes/functions.php on line 6031
```

Am actualizat funcția `register_rest_route` din modulul oblio și a dispărut.

Voi încerca un patch pentru asta.

Zi faină,
Vlad

**Comment by mateitudor** [comment]
Bună,
Oare e aceeași problemă pe care o am și eu?

Notice: Function ID was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('woocommerce_page_wc-orders'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Internal\Admin\Orders\PageController->output, Automattic\WooCommerce\Internal\Admin\Orders\Edit->display, Automattic\WooCommerce\Internal\Admin\Orders\Edit->render_meta_boxes, do_meta_boxes, _wp_oblio_order_details_invoice_box, include('/plugins/woocommerce-oblio/view/components/order_details_invoice_box.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in  /app/public/wp-includes/functions.php on line 6031

Nu pot să generez facturi.
Env: Local WP
Oblio v 1.0.52

**Comment by vladutilie** [comment]
Salut,

Sincer, nu cred că nu se pot genera facturi din cazua acelei notificări 🤔, cauza cred că este o eroare.

**Comment by MihaiCraciun88** [comment]
Buna ziua,

O sa ma uit peste problemele astea si o sa le rezolv saptamana asta.
Nu am apucat sa ma uit dar cred ca apar notice-urile alea doar daca este setat define( 'WP_DEBUG', true );

Ati putea sa imi spuneti si versiunea de php pe care o aveti daca nu puteti genera facturi?

Revin cu un update

**Comment by OblioSoftware** [comment]
Ok, am facut update 1.0.54
